markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->
paginate: 6
paginate_path: "/blog/page:num/"

include: 
  - "/games/index.html"
  - "/tools/index.html"